
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T17:52:58+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "adc0d317b2e6a4957cba84fca45c68828e67b73f",
 "version": "5.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
