
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-27T14:49:36+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "97ebc213ad4e19daac2a5596344136ee859db967",
 "version": "0.0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
