# Environment variables

# Kuroco
KUROCO_ENDPOINT = "KUROCO_ENDPOINT"
KUROCO_API_DOMAIN = "KUROCO_API_DOMAIN"
KUROCO_API_VERSION = "KUROCO_API_VERSION"
KUROCO_ACCESS_TOKEN = "KUROCO_ACCESS_TOKEN"

# Kuroco Responses
COLUMN_NAME_FOR_TOPICS_ID: str = "topics_id"