
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-27T15:26:19+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "bf0ddb6f8b4ab36d914799b6c12b037aa57f0d53",
 "version": "0.7.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
