
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-28T12:06:21-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "b5e8617dbfb1b525b62969c0fd1873b4b5c54bfa",
 "version": "0.27.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
