# autogenerated by: ./configure --with-types=hosts --with-module-name=vula --datadir=/var/lib/vula-organize/
EXTRA_CFLAGS=
EXTRA_CXXFLAGS=
HANDLE_pwd :=
HANDLE_grp :=
HANDLE_hosts := 1

MODULE_NAME := vula
DATADIR := /var/lib/vula-organize/
