# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phonexia/grpc/technologies/media_conversion/v1/media_conversion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from phonexia.grpc.common import core_pb2 as phonexia_dot_grpc_dot_common_dot_core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEphonexia/grpc/technologies/media_conversion/v1/media_conversion.proto\x12.phonexia.grpc.technologies.media_conversion.v1\x1a\x1fphonexia/grpc/common/core.proto\"\x8b\x01\n\x0e\x43onvertRequest\x12*\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x1b.phonexia.grpc.common.Audio\x12M\n\x06\x63onfig\x18\x02 \x01(\x0b\x32=.phonexia.grpc.technologies.media_conversion.v1.ConvertConfig\"\xaa\x01\n\rConvertConfig\x12_\n\x0c\x63hannel_mode\x18\x01 \x01(\x0e\x32I.phonexia.grpc.technologies.media_conversion.v1.ConvertConfig.ChannelMode\x12\x15\n\rkeep_channels\x18\x02 \x03(\x05\"!\n\x0b\x43hannelMode\x12\x07\n\x03MIX\x10\x00\x12\t\n\x05SPLIT\x10\x01\"P\n\rConvertResult\x12*\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x1b.phonexia.grpc.common.Audio\x12\x13\n\x0b\x63hannel_tag\x18\x02 \x01(\x05\"a\n\x0f\x43onvertResponse\x12N\n\x07results\x18\x01 \x03(\x0b\x32=.phonexia.grpc.technologies.media_conversion.v1.ConvertResult2\xa2\x01\n\x0fMediaConversion\x12\x8e\x01\n\x07\x43onvert\x12>.phonexia.grpc.technologies.media_conversion.v1.ConvertRequest\x1a?.phonexia.grpc.technologies.media_conversion.v1.ConvertResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phonexia.grpc.technologies.media_conversion.v1.media_conversion_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CONVERTREQUEST']._serialized_start=155
  _globals['_CONVERTREQUEST']._serialized_end=294
  _globals['_CONVERTCONFIG']._serialized_start=297
  _globals['_CONVERTCONFIG']._serialized_end=467
  _globals['_CONVERTCONFIG_CHANNELMODE']._serialized_start=434
  _globals['_CONVERTCONFIG_CHANNELMODE']._serialized_end=467
  _globals['_CONVERTRESULT']._serialized_start=469
  _globals['_CONVERTRESULT']._serialized_end=549
  _globals['_CONVERTRESPONSE']._serialized_start=551
  _globals['_CONVERTRESPONSE']._serialized_end=648
  _globals['_MEDIACONVERSION']._serialized_start=651
  _globals['_MEDIACONVERSION']._serialized_end=813
# @@protoc_insertion_point(module_scope)
