__version__ = '0.0.3'
__author__ = 'plotski'
__author_email__ = 'plotski@example.org'
__command_name__ = 'imgbox'
__homepage_url__ = 'https://codeberg.org/plotski/imgbox-cli'
__bugtracker_url__ = 'https://codeberg.org/plotski/imgbox-cli/issues'
