
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-28T16:07:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "499d6e416027fec2a9b6dd1cc4d7249b30a41463",
 "version": "0.7.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
