
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T17:21:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3bfb2683ee980b262e840941f5dd52c989aa4cb0",
 "version": "2.4.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
