CREATE VIEW ofb_17_nosurf_no_wigos AS
SELECT   
  expver                         as expver   ,    
  class                          as class    ,    
  stream                         as stream   ,    
  type                           as type     ,    
  andate                         as andate   ,    
  antime                         as antime   ,    
  reportype                      as reportype,    
  restricted                                 ,

  numtsl                                      ,

  timeslot                                    ,

  seqno                                       ,
  reportno                                    ,
  bufrtype                                    ,
  subtype                                     ,
  groupid                                     ,
  obstype                                     ,
  codetype                                    ,
  sensor                                      ,
  statid                                      ,
  date                                        ,
  time                                        ,
  rdbdate                                           ,
  rdbtime                                           ,
  report_status                               ,    
  report_event1                               ,    
  report_rdbflag                              ,    
  degrees(lat)           as lat@hdr           ,    
  degrees(lon)           as lon@hdr           ,    

  lsm@modsurf                                 ,
  orography@modsurf                           ,
  stalt                                       ,
  sonde_type                                  ,
  station_type                                ,
  
  entryno                                     ,
  obsvalue                                    ,
  varno                                       ,
  vertco_type                                 ,
  vertco_reference_1                          ,
  ppcode                                      ,
  flight_phase                                ,
  aircraft_type                               ,
  heading                                     ,
  level@conv_body                             ,

  datum_anflag                                ,    
  datum_status@body                                ,    
  datum_event1@body                                ,    
  datum_rdbflag                               ,    
  biascorr                                    ,
  biascorr_fg                                    ,
  qc_pge                                      ,
  an_depar@body                                    ,
  fg_depar@body                                    ,
  obs_error                                   ,
  final_obs_error                                   ,
  fg_error                                    ,
  eda_spread                                  ,
  datum_status_hires@update_1                        ,

FROM desc, timeslot_index, hdr, modsurf, conv, body, errstat, conv_body, update_1
WHERE reportype is not null
AND groupid=17;
