# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_strs.ipynb.

# %% auto 0
__all__ = ['shiftcycle']

# %% ../nbs/00_strs.ipynb 6
import string
from itertools import islice, cycle

# %% ../nbs/00_strs.ipynb 8
#| export


# %% ../nbs/00_strs.ipynb 11
#| export

# %% ../nbs/00_strs.ipynb 13
try: import numpy as np, pandas as pd
except ImportError: ...

# %% ../nbs/00_strs.ipynb 15
#| export


# %% ../nbs/00_strs.ipynb 17
#| export


# %% ../nbs/00_strs.ipynb 19
#| export


# %% ../nbs/00_strs.ipynb 21
#| export


# %% ../nbs/00_strs.ipynb 23
def shiftcycle(c: str = 'x', chars: str = string.ascii_lowercase):
    shift = len(chars) - chars.index(c)
    beg = 1 * len(chars) - shift
    end = 2 * len(chars) - shift  
    return ''.join(islice(cycle(chars), beg, end))

# %% ../nbs/00_strs.ipynb 25
#| export

