
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T07:19:14+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "220454f6445a7a0e0d72c3058195068ae423170a",
 "version": "1.20.0.post0.dev36"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
