# Generated by Django 4.2.7 on 2023-11-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='type',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='type',
            new_name='identifier',
        ),
    ]
