# coding: utf-8

# flake8: noqa
"""
    rtu mirea vuc schedule

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from rtu_mirea_vuc_schedule_client.models.course_dir import CourseDir
from rtu_mirea_vuc_schedule_client.models.day import Day
from rtu_mirea_vuc_schedule_client.models.day_result import DayResult
from rtu_mirea_vuc_schedule_client.models.http_validation_error import HTTPValidationError
from rtu_mirea_vuc_schedule_client.models.lesson import Lesson
from rtu_mirea_vuc_schedule_client.models.platoon import Platoon
from rtu_mirea_vuc_schedule_client.models.schedule_result import ScheduleResult
from rtu_mirea_vuc_schedule_client.models.shape import Shape
from rtu_mirea_vuc_schedule_client.models.subject import Subject
from rtu_mirea_vuc_schedule_client.models.validation_error import ValidationError
from rtu_mirea_vuc_schedule_client.models.validation_error_loc_inner import ValidationErrorLocInner
from rtu_mirea_vuc_schedule_client.models.week_schedule import WeekSchedule
from rtu_mirea_vuc_schedule_client.models.week_schedule_result import WeekScheduleResult
from rtu_mirea_vuc_schedule_client.models.workbook_file import WorkbookFile
from rtu_mirea_vuc_schedule_client.models.workbook_settings import WorkbookSettings
