
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T10:02:32-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "bcc02d80e40f4f61ef2db6f567f9acb69c64a496",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
