# Generated by Django 4.2.7 on 2023-11-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mytree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tree_root', to='mytree.treenode')),
            ],
        ),
    ]
