
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T01:33:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5fb22d7f8957e7ac3d4c94f9b163180654fc1c1",
 "version": "1.20.0.post0.dev16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
