from setuptools import setup

readme =open("./README.md", "r")

setup(
    
    name='zzmtrgd',
    packages = ['zzmtrgd'],
    version = '0.9.2',
    description = 'Metodo MTR',
    long_description = readme.read(),
    long_description_content_type = 'text/markdown',
    author_email = 'ramosjack066@gmail.com',
    keywords=['testing', 'example'],
    classifiers = [],
    license= 'MIT',
    include_package_data = True,
    install_requires = [
        'certifi==2023.7.22',
        'charset-normalizer==3.3.1',
        'contourpy==1.2.0',
        'cycler==0.12.1',
        'docutils==0.20.1',
        'et-xmlfile==1.1.0',
        'fonttools==4.44.0',
        'idna==3.4',
        'importlib-metadata==6.8.0',
        'jaraco.classes==3.3.0',
        'joblib==1.3.2',
        'keyring==24.2.0',
        'kiwisolver==1.4.5',
        'markdown-it-py==3.0.0',
        'matplotlib==3.8.1',
        'mdurl==0.1.2',
        'more-itertools==10.1.0',
        'nh3==0.2.14',
        'numpy==1.26.0',
        'openpyxl==3.1.2',
        'packaging==23.2',
        'pandas==2.1.2',
        'Pillow==10.1.0',
        'pkginfo==1.9.6',
        'Pygments==2.16.1',
        'pyparsing==3.1.1',
        'python-dateutil==2.8.2',
        'pytz==2023.3.post1',
        'pywin32-ctypes==0.2.2',
        'readme-renderer==42.0',
        'requests==2.31.0',
        'requests-toolbelt==1.0.0',
        'rfc3986==2.0.0',
        'rich==13.6.0',
        'scikit-learn==1.3.1',
        'scikit-multilearn==0.2.0',
        'scipy==1.11.3',
        'six==1.16.0',
        'sklearn==0.0.post10',
        'threadpoolctl==3.2.0',
        'twine==4.0.2',
        'tzdata==2023.3',
        'urllib3==2.0.7',
        'zipp==3.17.0',

    ],
)
