# trunk-ignore(ruff/B018)
{
    "name": "HR Attendance Mitxelena",
    "license": "AGPL-3",
    "version": "14.0.1.0.22",
    "category": "Human Resources",
    "sequence": 20,
    "summary": "Employee Attendances Customizations for Mitxelena",
    "website": "https://git.coopdevs.org/coopdevs/odoo/odoo-addons/odoo-mitxelena",
    "author": "Coopdevs Treball SCCL",
    "depends": [
        "base",
        "base_automation",
        "hr",
        "hr_attendance",
        "hr_attendance_validation",
        "hr_entry_type_mitxelena",
    ],
    "data": [
        "data/hr_attendance_automated_action.xml",
        "data/hr_attendance_server_action.xml",
        "data/hr_leave_allocation_cron.xml",
        "data/resource_calendar_cron.xml",
        "data/resource_calendar_data.xml",
        "reports/attendance_report_template.xml",
        "security/ir.model.access.csv",
        "views/hr_attendance_validation_views.xml",
        "views/hr_attendance_views.xml",
        "views/hr_employee_views.xml",
        "views/resource_calendar_views.xml",
        "views/reset.xml",
        "wizards/attendance_report_wizard_view.xml",
    ],
    "demo": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
