# Generated by Django 4.2.7 on 2023-11-21 14:35
from __future__ import annotations

from django.db import migrations, models

import pretix.base.models.base


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DestinatarioFatturaElettronica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("codice_destinatario", models.CharField(max_length=7)),
                ("pec_address", models.EmailField(max_length=100, null=True)),
            ],
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
    ]
