# Autogenerated by devscripts/update-version.py

__version__ = '2023.11.26.232703'

RELEASE_GIT_HEAD = '9751a457cfdb18bf99d9ee0d10e4e6a594502bbf'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2023.11.26.232703dev'
