
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T22:55:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "526e61dea085a0c32ea91b2451fda36e1072451f",
 "version": "0.1.159"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
