
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-25T01:09:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bd05f62a69f6d0dd9c1fbf12f966d20002e3768e",
 "version": "1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
