CREATE VIEW ofb_8 AS 

SELECT 

// Insert constant columns here 
expver@desc as expver, 
class@desc as class, 
stream@desc as stream, 
type@desc as type, 
andate@desc as andate, 
antime@desc as antime, 
reportype@hdr as reportype, 
numtsl@desc, 
mxup_traj@desc, 

// Insert hdr-aligned columns here 
date@hdr, 
rdbdate@hdr, 
lsm@modsurf, 
seaice@modsurf, 
restricted@hdr, 
timeslot@timeslot_index, 
seqno@hdr, 
bufrtype@hdr, 
subtype@hdr, 
groupid@hdr, 
obstype@hdr, 
codetype@hdr, 
sensor@hdr, 
time@hdr, 
rdbtime@hdr, 
report_status@hdr, 
report_event1@hdr, 
report_rdbflag@hdr, 
degrees(lat@hdr) as lat@hdr, 
degrees(lon@hdr) as lon@hdr, 
reportno@hdr, 
azimuth@sat, 
undulation@gnssro, 
radcurv@gnssro, 
retrtype@hdr, 
satellite_identifier@sat, 

// Insert body-aligned columns here 
entryno@body, 
vertco_reference_1@body, 
obsvalue@body, 
varno@body, 
vertco_type@body, 
datum_anflag@body, 
datum_status@body, 
datum_event1@body, 
datum_rdbflag@body, 
biascorr@body, 
biascorr_fg@body, 
qc_pge@body, 
an_depar@body, 
fg_depar@body, 
datum_status_hires@update_1, 
obs_error@errstat, 
final_obs_error@errstat, 
fg_error@errstat, 
eda_spread@errstat, 
jacobian_peak@body, 
fc_sens_obs@body, 
vertco_reference_2@body, 
an_sens_obs@body, 
hires@update_2

WHERE groupid@hdr == 8 ;
