# Autogenerated by devscripts/update-version.py

__version__ = '2023.11.28.232715'

RELEASE_GIT_HEAD = '15f22b4880b6b3f71f350c64d70976ae65b9f1ca'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2023.11.28.232715dev'
