
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-27T21:26:41+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "0eb4cbe424d5e9d76e9598d03d5f583ae4568afc",
 "version": "0.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
