
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-25T22:18:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8440b4bb3aa56fb7b558efb00f084087b3e88e18",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
