# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20036_information_mr_info_adp_info import InlineResponse20036InformationMrInfoAdpInfo  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20036InformationMrInfoAdpInfo(unittest.TestCase):
    """InlineResponse20036InformationMrInfoAdpInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20036InformationMrInfoAdpInfo(self):
        """Test InlineResponse20036InformationMrInfoAdpInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20036_information_mr_info_adp_info.InlineResponse20036InformationMrInfoAdpInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
