# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20036_drives import InlineResponse20036Drives  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20036Drives(unittest.TestCase):
    """InlineResponse20036Drives unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20036Drives(self):
        """Test InlineResponse20036Drives"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20036_drives.InlineResponse20036Drives()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
