# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: 23.09
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20052_security import InlineResponse20052Security  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20052Security(unittest.TestCase):
    """InlineResponse20052Security unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20052Security(self):
        """Test InlineResponse20052Security"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20052_security.InlineResponse20052Security()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
