# Generated by Django 4.2.7 on 2023-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edc_form_runners", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="issue",
            name="unique_label_lower_subject_identifier_etc",
        ),
        migrations.AddField(
            model_name="issue",
            name="schedule_name",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="visit_schedule_name",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="label_lower",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="issue",
            name="subject_identifier",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="issue",
            name="visit_code",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="issue",
            name="visit_code_sequence",
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name="issue",
            constraint=models.UniqueConstraint(
                fields=(
                    "label_lower",
                    "subject_identifier",
                    "field_name",
                    "visit_code",
                    "visit_code_sequence",
                    "visit_schedule_name",
                    "schedule_name",
                ),
                name="unique_label_lower_subject_identifier_etc",
            ),
        ),
    ]
