
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-28T12:55:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1f87ed16ad412023e2c23dede1dbb63eb64f9188",
 "version": "0.7.0b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
