
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-21T16:41:51-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3de4c25d287bad937a7fc7b54b4120938da23c8",
 "version": "2.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
