SYMBOL              ='symbol'
OTYPE               ='otype'
OPEN_ACTION         ='open_action'
OPEN                ='open'
HIGH                ='high'
LOW                 ='low'
CLOSE               ='close'
BID_SIZE            ='bidSize'
ASK_SIZE            ='askSize'
VOLUME              ='volume'

EXP_DATE            ='exp_date'
STRIKE              ='strike'
PRICE               ='price'
LAST_PRICE          ='lastPrice'
BID                 ='bid'
ASK                 ='ask'
VOLUME              ='volume'
OPEN_INTEREST       ='openInterest'
IMPLIED_VOLATILITY  ='impliedVolatility'

DELTA               ='delta'
GAMMA               ='gamma'
VEGA                ='vega'
THETA               ='theta'
SIGMA               ='sigma'

DAYS_TO_EXPIRE      ='days to expire'
IN_MONEY            = 'in money'
BID_ASK_SPREAD      ='bid ask spread'
STOCK_PRICE         ='stock_price'
#BREAKEVEN_LONG      = 'breakeven_long'
#BREAKEVEN_SHORT     = 'breakeven_short'
#WIN_PROB_LONG       = 'win_prob_long'
#WIN_PROB_SHORT      = 'win_prob_short'
BREAKEVEN           = 'breakeven'
WIN_PROB            = 'win_prob'