# __init__.py

from pixel_perfect.image_comparer import image_similarity
from pixel_perfect.utils import assert_elements_screenshots
from pixel_perfect.utils import take_screenshots_by_xpath
from pixel_perfect.utils import take_screenshot_by_xpath
from pixel_perfect.utils import click_element_by_xpath
from pixel_perfect.utils import get_image_offset_ratio_xpath
from pixel_perfect.utils import get_count
from pixel_perfect.utils import get_image_offset_ratio
from pixel_perfect.utils import get_text_by_xpath
from pixel_perfect.utils import get_element_by_xpath
from pixel_perfect.utils import get_property_by_xpath
from pixel_perfect.utils import get_image_aspect_ratio