from setuptools import setup, find_packages

setup(
    name='Question',
    version='0.1.0',
    packages=find_packages(), 
    install_requires=[
         'certifi==2023.11.17',
        'charset-normalizer==3.3.2',
        'colorama==0.4.6',
        'distlib==0.3.7',
        'docutils==0.20.1',
        'et-xmlfile==1.1.0',
        'filelock==3.13.1',
        'idna==3.4',
        'importlib-metadata==6.8.0',
        'jaraco.classes==3.3.0',
        'keyring==24.3.0',
        'markdown-it-py==3.0.0',
        'mdurl==0.1.2',
        'more-itertools==10.1.0',
        'nh3==0.2.14',
        'numpy==1.26.0',
        'openpyxl==3.1.2',
        'pandas==2.1.1',
        'Pillow==10.1.0',
        'pipdeptree==2.13.1',
        'pkginfo==1.9.6',
        'platformdirs==4.0.0',
        'Pygments==2.17.2',
        'python-dateutil==2.8.2',
        'pytz==2023.3.post1',
        'pywin32-ctypes==0.2.2',
      'QUESTIONBANK==1.82.2',

        'readme-renderer==42.0',
        'reportlab==4.0.7',
        'requests==2.31.0',
        'requests-toolbelt==1.0.0',
        'rfc3986==2.0.0',
        'rich==13.7.0',
        'six==1.16.0',
        'tqdm==4.66.1',
        'twine==4.0.2',
        'tzdata==2023.3',
        'urllib3==2.1.0',
        'virtualenv==20.24.7',
        
    ],
   
    author='Ish',
    author_email='tiwaryishita52@example.com',
    description="This is automatic generating question software",
   
    license='MIT', 
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
    ],
)
