"""Generated declinate CLI tests."""

# DO NOT EDIT THIS FILE MANUALLY

import inspect

from declinate.check import check_package
from declinate.cli import main


def test_cli_is_up_to_date() -> None:
    """Test if compiled cli is up to date."""
    assert not (res := check_package('declinate')), res


def test_cli() -> None:
    """Cli."""
    assert inspect.isfunction(main)
