# https://ffmpeg.org/ffmpeg-codecs.html

FFMPEG_PIX_FMT_BGR24 = "bgr24"
FFMPEG_PIX_FMT_GRAY8 = "gray8"
FFMPEG_PIX_FMT_RGB24 = "rgb24"
FFMPEG_PIX_FMT_RGBA = "rgba"
FFMPEG_PIX_FMT_YUV420P = "yuv420p"
FFMPEG_PIX_FMT_YUYV422 = "yuyv422"

FFMPEG_VCODEC_LIBX264 = "libx264"
FFMPEG_VCODEC_LIBX265 = "libx265"

FFMPEG_LOG_LEVEL_QUIET = "quiet"
FFMPEG_LOG_LEVEL_PANIC = "panic"
FFMPEG_LOG_LEVEL_FATAL = "fatal"
FFMPEG_LOG_LEVEL_ERROR = "error"
FFMPEG_LOG_LEVEL_WARNING = "warning"
FFMPEG_LOG_LEVEL_INFO = "info"
FFMPEG_LOG_LEVEL_DEBUG = "debug"
