
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-30T14:41:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a6bb66a4b9c66926a95ef8613022a596981ed24",
 "version": "0.8.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
