US_STATES = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawái",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Luisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Míchigan",
    "Minnesota",
    "Misisipi",
    "Misuri",
    "Montana",
    "Nebraska",
    "Nevada",
    "Nuevo Hampshire",
    "Nueva Jersey",
    "Nuevo México",
    "Nueva York",
    "Carolina del Norte",
    "Dakota del Norte",
    "Ohio",
    "Oklahoma",
    "Oregón",
    "Pensilvania",
    "Rhode Island",
    "Carolina del Sur",
    "Dakota del Sur",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "Virginia Occidental",
    "Wisconsin",
    "Wyoming",
]
ADDRESS_TYPE = ["DOM", "FGN", "MIL"]
MEDICAL_UNIVERSITIES_USA = [
    "Harvard University - Harvard Medical School",
    "Stanford University - Stanford School of Medicine",
    "Johns Hopkins University - Johns Hopkins School of Medicine",
    "Yale University - Yale School of Medicine",
    "University of California, San Francisco - UCSF School of Medicine",
    "Columbia University - Vagelos College of Physicians and Surgeons",
    "University of Pennsylvania - Perelman School of Medicine",
    "University of Chicago - Pritzker School of Medicine",
    "Washington University in St. Louis - Washington University School of Medicine",
    "Duke University - Duke University School of Medicine",
    "University of Michigan - Michigan Medicine",
    "Vanderbilt University - Vanderbilt University School of Medicine",
    "University of California, Los Angeles - David Geffen School of Medicine",
    "University of North Carolina at Chapel Hill - UNC School of Medicine",
    "University of Washington - UW School of Medicine",
    "Emory University - Emory University School of Medicine",
    "University of Virginia - UVA School of Medicine",
    "Baylor College of Medicine",
    "Mayo Clinic College of Medicine and Science",
    "University of Texas Southwestern Medical Center - UT Southwestern Medical School",
]
ISO_639_LANGUAGES = [
    ("Abkhazian", "ab"),
    ("Afar", "aa"),
    ("Afrikaans", "af"),
    ("Akan", "ak"),
    ("Albanian", "sq"),
    ("Amharic", "am"),
    ("Arabic", "ar"),
    ("Aragonese", "an"),
    ("Armenian", "hy"),
    ("Assamese", "as"),
    ("Avaric", "av"),
    ("Avestan", "ae"),
    ("Aymara", "ay"),
    ("Azerbaijani", "az"),
    ("Bambara", "bm"),
    ("Bashkir", "ba"),
    ("Basque", "eu"),
    ("Belarusian", "be"),
    ("Bengali, Bangla", "bn"),
    ("Bihari", "bh"),
    ("Bislama", "bi"),
    ("Bosnian", "bs"),
    ("Breton", "br"),
    ("Bulgarian", "bg"),
    ("Burmese", "my"),
    ("Catalan", "ca"),
    ("Chamorro", "ch"),
    ("Chechen", "ce"),
    ("Chichewa, Chewa, Nyanja", "ny"),
    ("Chinese", "zh"),
    ("Chuvash", "cv"),
    ("Cornish", "kw"),
    ("Corsican", "co"),
    ("Cree", "cr"),
    ("Croatian", "hr"),
    ("Czech", "cs"),
    ("Danish", "da"),
    ("Divehi, Dhivehi, Maldivian", "dv"),
    ("Dutch", "nl"),
    ("Dzongkha", "dz"),
    ("English", "en"),
    ("Esperanto", "eo"),
    ("Estonian", "et"),
    ("Ewe", "ee"),
    ("Faroese", "fo"),
    ("Fijian", "fj"),
    ("Finnish", "fi"),
    ("French", "fr"),
    ("Frisian", "fy"),
    ("Fulah", "ff"),
    ("Galician", "gl"),
    ("Ganda", "lg"),
    ("Georgian", "ka"),
    ("German", "de"),
    ("Greek", "el"),
    ("Guaraní", "gn"),
    ("Gujarati", "gu"),
    ("Haitian, Haitian Creole", "ht"),
    ("Hausa", "ha"),
    ("Hebrew (modern)", "he"),
    ("Herero", "hz"),
    ("Hindi", "hi"),
    ("Hiri Motu", "ho"),
    ("Hungarian", "hu"),
    ("Interlingua", "ia"),
    ("Indonesian", "id"),
    ("Interlingue", "ie"),
    ("Irish", "ga"),
    ("Igbo", "ig"),
    ("Inupiaq", "ik"),
    ("Ido", "io"),
    ("Icelandic", "is"),
    ("Italian", "it"),
    ("Inuktitut", "iu"),
    ("Japanese", "ja"),
    ("Javanese", "jv"),
    ("Kalaallisut, Greenlandic", "kl"),
    ("Kannada", "kn"),
    ("Kanuri", "kr"),
    ("Kashmiri", "ks"),
    ("Kazakh", "kk"),
    ("Khmer", "km"),
    ("Kikuyu, Gikuyu", "ki"),
    ("Kinyarwanda", "rw"),
    ("Kirghiz, Kyrgyz", "ky"),
    ("Komi", "kv"),
    ("Kongo", "kg"),
    ("Korean", "ko"),
    ("Kurdish", "ku"),
    ("Kwanyama, Kuanyama", "kj"),
    ("Latin", "la"),
    ("Luxembourgish, Letzeburgesch", "lb"),
    ("Ganda", "lg"),
    ("Lingala", "ln"),
    ("Lao", "lo"),
    ("Lithuanian", "lt"),
    ("Luba-Katanga", "lu"),
    ("Latvian", "lv"),
    ("Manx", "gv"),
    ("Macedonian", "mk"),
    ("Malagasy", "mg"),
    ("Malay", "ms"),
    ("Malayalam", "ml"),
    ("Maltese", "mt"),
    ("Maori", "mi"),
    ("Marathi (Mara?hi)", "mr"),
    ("Marshallese", "mh"),
    ("Mongolian", "mn"),
    ("Nauru", "na"),
    ("Navajo, Navaho", "nv"),
    ("Norwegian Bokmål", "nb"),
    ("North Ndebele", "nd"),
    ("Nepali", "ne"),
    ("Ndonga", "ng"),
    ("Norwegian Nynorsk", "nn"),
    ("Norwegian", "no"),
    ("Nuosu", "ii"),
    ("South Ndebele", "nr"),
    ("Occitan", "oc"),
    ("Ojibwe, Ojibwa", "oj"),
    (
        "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic",
        "cu",
    ),
    ("Oromo", "om"),
    ("Oriya", "or"),
    ("Ossetian, Ossetic", "os"),
    ("Panjabi, Punjabi", "pa"),
    ("Pali", "pi"),
    ("Persian", "fa"),
    ("Polish", "pl"),
    ("Pashto, Pushto", "ps"),
    ("Portuguese", "pt"),
    ("Quechua", "qu"),
    ("Romansh", "rm"),
    ("Kirundi", "rn"),
    ("Russian", "ru"),
    ("Sanskrit", "sa"),
    ("Sardinian", "sc"),
    ("Sindhi", "sd"),
    ("Northern Sami", "se"),
    ("Samoan", "sm"),
    ("Sango", "sg"),
    ("Serbian", "sr"),
    ("Gaelic, Scottish Gaelic", "gd"),
    ("Shona", "sn"),
    ("Sinhalese, Sinhala", "si"),
    ("Slovak", "sk"),
    ("Slovene", "sl"),
    ("Somali", "so"),
    ("Southern Sotho", "st"),
    ("Spanish", "es"),
    ("Sundanese", "su"),
    ("Swahili", "sw"),
    ("Swati", "ss"),
    ("Swedish", "sv"),
    ("Tamil", "ta"),
    ("Telugu", "te"),
    ("Tajik", "tg"),
    ("Thai", "th"),
    ("Tigrinya", "ti"),
    ("Tibetan", "bo"),
    ("Turkmen", "tk"),
    ("Tagalog", "tl"),
    ("Tswana", "tn"),
    ("Tonga (Tonga Islands)", "to"),
    ("Turkish", "tr"),
    ("Tsonga", "ts"),
    ("Tatar", "tt"),
    ("Twi", "tw"),
    ("Tahitian", "ty"),
    ("Uighur, Uyghur", "ug"),
    ("Ukrainian", "uk"),
    ("Urdu", "ur"),
    ("Uzbek", "uz"),
    ("Venda", "ve"),
    ("Vietnamese", "vi"),
    ("Volapük", "vo"),
    ("Walloon", "wa"),
    ("Welsh", "cy"),
    ("Wolof", "wo"),
    ("Western Frisian", "fy"),
    ("Xhosa", "xh"),
    ("Yiddish", "yi"),
    ("Yoruba", "yo"),
    ("Zhuang, Chuang", "za"),
    ("Zulu", "zu"),
]
ETHNICITY: dict = {
    "0": "UNKNOWN/NOT DISCLOSED",
    "1": "WHITE (CAUCASIAN)",
    "2": "HISPANIC/LATINO",
    "3": "BLACK (AFRICAN AMERICAN)",
    "4": "ASIAN/PACIFIC ISLANDER",
    "5": "AMERICAN INDIAN/ALASKAN",
    "7": "FILIPINO",
    "A": "AMERASIAN",
    "C": "CHINESE",
    "H": "CAMBODIAN",
    "J": "JAPANESE",
    "K": "KOREAN",
    "M": "SAMOAN",
    "N": "ASIAN INDIAN",
    "P": "HAWAIIAN",
    "R": "GUAMANIAN",
    "T": "LAOTIAN",
    "V": "VIETNAMESE",
    "Z": "OTHER",
}
MALPRACTICE_INSURANCE = [
    "Admiral Insurance Company",
    "The Doctor's Company",
    "The Doctors Company",
    "HRSA (Federal Torts Claim Act)",
    "NORCAL Mutual Insurance Company",
    "Norcal Mutual Insurance Co",
    "Cooperative of American Physicians",
    "Lancet Indemnity Insurance",
    "Beta Healthcare Group",
    "General Star Indemnity Company",
    "OMIC Ophthalmic Mutual Insurance Company",
    "Cooperative of American Physicians, Inc.",
    "Doctor's Company Insurance Group",
    "Fairway Physicians Ins. Co.",
    "Medical Protective Company",
    "Accord",
    "United States Liability Insurance Company",
    "Hallmark Specialty Insurance Company",
    "COOPERATIVE  OF AMERICAN PHYSICIANS",
    "CAP/MPT",
    "Lancet Indemnity, RRG",
    "CARE Risk Retention Group, INC",
    "Landmark American Insurance Co.",
    "Desert Mountain Insurance Services, Inc.",
    "AMS Risk Retention Group Inc.",
    "AMS Risk Retention Group",
    "AMS Risk Retention Group Inc.",
    "AMS Risk Retention Group Inc.",
    "Superior Malpractice Insurance Services, Inc.",
    "Ophthalmic Mutual Ins Co Rrg",
    "Medical Insurance Exchange of California",
    "Applied Medico-Legal Solutions RRG, Inc.",
    "Preferred Professional Insurance Company",
    "PPIC Insurance",
    "Liberty Insurance Underwriters Inc.",
    "BETA HealthCare Group",
    "American Casualty Company of Reading, PA",
    "NORCAL MUTUAL INSURANCE COMPANY",
    "Mutual Protection Trust",
    "Nurses Service Organization - CNA",
    "Mutual Protection Trust",
    "The Medical Protective Company",
    "MUTUAL PROTECTION TRUST",
    "Steadfast Ins Co",
    "PICA Mutual INS Company",
    "Podiatry Insurance Company of America",
    "PICA Treated Fairly",
    "The Podiatry Insurance Company of America",
    "Mercer Consumer",
]
ENDPOINT_TYPE = {
    "DIRECT": "Direct Messaging Address",
    "CONNECT": "CONNECT URL",
    "OTHERS": "Other URL",
    "FHIR": "FHIR URL",
    "SOAP": "SOAP URL",
}
ENDPOINT_USE = {
    "DIRECT": "Direct",
    "HIE": "Health Information Exchange (HIE)",
    "OTHER": "Other",
}
ENDPOINT_CONTENT_OTHER_DESCRIPTION = [
    "OTHER",
    "CSV",
    "EMAIL",
    "Communication",
    "Standard Direct Functionality",
    "unknown",
    "website",
    "CDA/CCD/TXT",
    "CDA/PDF/TXT",
    "Excel file",
]
CREDENTIAL = ["DMD", "PhD", "MD", "Dr"]
OFFICIAL_TITLE_POSITION = [
    "ACCOUNT MANAGER",
    "ACUPUNCTURIST",
    "ADMIN ASSISTANT",
    "CEO & FOUNDER",
    "CHIEF ACCOUNTING OFFICER",
    "DAYCARE DIRECTOR",
    "DENTIST OWNER",
    "DIRECTOR OF FINANCE",
    "EXECUTIVE DIRECTOR",
    "FNP OWNER",
    "FOUNDER & CEO",
    "GENERAL DENTIST",
    "HEALTH DIRECTOR",
    "HOSPITAL ADMINISTRATOR",
    "INSURANCE COORDINATOR",
    "LAB DIRECTOR",
    "LCSW",
    "LICENSED PSYCHOLOGIST",
    "LMFT",
    "LPC"
]
