
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T09:42:28+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "ef8c5169c6e491b81c07e1ac36e23606040e3c8b",
 "version": "0.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
