
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-28T13:33:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "02bb02753d35c87af95f245ce05bd6bbee542550",
 "version": "1.62.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
