# Generated by Django 4.2.7 on 2023-11-21 14:35
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pretixbase", "0001_initial"),
        ("pretix_fattura_elettronica", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destinatariofatturaelettronica",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dest_fattura_elettronica_order",
                to="pretixbase.order",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="destinatariofatturaelettronica",
            unique_together={("order", "codice_destinatario")},
        ),
    ]
