from pebbleauthclient import auth

auth_token = auth("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImVudGl0bGVtZW50Ijo5OTQsImtpZCI6IjEzQ1pmSlhkblVKWlhBLW13MGhnSEI2bjl4ODVqQTVZeDRvdjNRTmlBNmsifQ.eyJpc3MiOiJEaW5vQ2hpZXNhLmdpdGh1Yi5pbyIsInN1YiI6ImtpbmEiLCJhdWQiOiJhbG1hIiwiaWF0IjoxNzAxMzMyNTY3LCJleHAiOjE3MDEzMzMxNjcsImNsYXNzaWQiOnRydWV9.VGnMHZBwWeC_ybuGOIU2l1HT-nIrXWlsr1tRA1a2Gd0T7GqsVOc91PrklZ0cchZi4pZG7ptWXebAVLDLpmYsFct9JzjhbCbWefgwPfXvWpr5k4CrfAI4aV96wR1OifSEqVEbXr3bKwPdb1mGovhrO_mNtcvYRqsi2JJTdPFE1yuEbG13UtpgjcmOjdjnVarw6ebAOTAgd5l4Jdw3KKYBluKFsuAtndK5ENUWp3ls73VL1Gp-aiDEne-6I0YpUqZien1UssCBbKv1tILCWWCmR6KcW-c0sswzBdB8FqdVNYVKWMs8_nyySDLlGM4R3EgjFLXOi3SeiyhMu5fG379aow")
user = auth_token.get_user()
licence = auth_token.get_authenticated_licence()

print(auth_token)
print(user)
print(licence)
