
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-28T19:59:48-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "69240ecaaa667f4bbffb52c3951544467b176db9",
 "version": "6.24.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
