
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T16:50:34+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e51ff8ea9c56d114a3947a419e9b2fbb7ca0da9",
 "version": "2.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
