# coding: utf-8

"""
    PDS Registry Search API

    Registry API enabling advanced search on PDS data and metadata. The API provides end-points to search for bundles, collections and any PDS products with advanced search queries. It also enables to browse the archive hierarchically downward (e.g. collection/s products) or upward (e.g. bundles containing a product).   # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: pds-operator@jpl.nasa.gov
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import pds.api_client
from pds.api_client.api.deprecated_api import DeprecatedApi  # noqa: E501
from pds.api_client.rest import ApiException


class TestDeprecatedApi(unittest.TestCase):
    """DeprecatedApi unit test stubs"""

    def setUp(self):
        self.api = pds.api_client.api.deprecated_api.DeprecatedApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bundle_list(self):
        """Test case for bundle_list

        deprecated  # noqa: E501
        """
        pass

    def test_bundles_lidvid(self):
        """Test case for bundles_lidvid

        deprecated  # noqa: E501
        """
        pass

    def test_bundles_lidvid_all(self):
        """Test case for bundles_lidvid_all

        deprecated  # noqa: E501
        """
        pass

    def test_bundles_lidvid_collections(self):
        """Test case for bundles_lidvid_collections

        deprecated  # noqa: E501
        """
        pass

    def test_bundles_lidvid_collections_all(self):
        """Test case for bundles_lidvid_collections_all

        deprecated  # noqa: E501
        """
        pass

    def test_bundles_lidvid_collections_latest(self):
        """Test case for bundles_lidvid_collections_latest

        deprecated  # noqa: E501
        """
        pass

    def test_bundles_lidvid_latest(self):
        """Test case for bundles_lidvid_latest

        deprecated  # noqa: E501
        """
        pass

    def test_bundles_lidvid_products(self):
        """Test case for bundles_lidvid_products

        deprecated  # noqa: E501
        """
        pass

    def test_class_member_of(self):
        """Test case for class_member_of

        returns one or more PDS Products that have the given PDS product class and lid/lidvid as a member.   # noqa: E501
        """
        pass

    def test_class_member_of_of(self):
        """Test case for class_member_of_of

        returns one or more PDS Products that have the given PDS product class and lid/lidvid as a member of its members.   # noqa: E501
        """
        pass

    def test_class_member_of_of_vers(self):
        """Test case for class_member_of_of_vers

        returns one or more PDS Products that have the given PDS product class and lid/lidvid as a member of its members.   # noqa: E501
        """
        pass

    def test_class_member_of_vers(self):
        """Test case for class_member_of_vers

        returns one or more PDS Products that have the given PDS product class and lid/lidvid as a member.   # noqa: E501
        """
        pass

    def test_class_members(self):
        """Test case for class_members

        returns one or more PDS Products that are members of the given PDS product class and lid/lidvid.   # noqa: E501
        """
        pass

    def test_class_members_members(self):
        """Test case for class_members_members

        returns one or more PDS Products that are the members of the members of the given PDS product class and lid/lidvid.   # noqa: E501
        """
        pass

    def test_class_members_members_vers(self):
        """Test case for class_members_members_vers

        returns one or more PDS Products that are the members of the members of the given PDS product class and lid/lidvid.   # noqa: E501
        """
        pass

    def test_class_members_vers(self):
        """Test case for class_members_vers

        returns one or more PDS Products that are members of the given PDS product class and lid/lidvid.   # noqa: E501
        """
        pass

    def test_collection_list(self):
        """Test case for collection_list

        deprecated  # noqa: E501
        """
        pass

    def test_collections_lidvid(self):
        """Test case for collections_lidvid

        deprecated  # noqa: E501
        """
        pass

    def test_collections_lidvid_all(self):
        """Test case for collections_lidvid_all

        deprecated  # noqa: E501
        """
        pass

    def test_collections_lidvid_bundles(self):
        """Test case for collections_lidvid_bundles

        deprecated  # noqa: E501
        """
        pass

    def test_collections_lidvid_latest(self):
        """Test case for collections_lidvid_latest

        deprecated  # noqa: E501
        """
        pass

    def test_collections_lidvid_products(self):
        """Test case for collections_lidvid_products

        deprecated  # noqa: E501
        """
        pass

    def test_collections_lidvid_products_all(self):
        """Test case for collections_lidvid_products_all

        deprecated  # noqa: E501
        """
        pass

    def test_collections_lidvid_products_latest(self):
        """Test case for collections_lidvid_products_latest

        deprecated  # noqa: E501
        """
        pass

    def test_products_lidivid_bundles_all(self):
        """Test case for products_lidivid_bundles_all

        deprecated  # noqa: E501
        """
        pass

    def test_products_lidvid_bundles(self):
        """Test case for products_lidvid_bundles

        deprecated  # noqa: E501
        """
        pass

    def test_products_lidvid_bundles_latest(self):
        """Test case for products_lidvid_bundles_latest

        deprecated  # noqa: E501
        """
        pass

    def test_products_lidvid_collections(self):
        """Test case for products_lidvid_collections

        deprecated  # noqa: E501
        """
        pass

    def test_products_lidvid_collections_all(self):
        """Test case for products_lidvid_collections_all

        deprecated  # noqa: E501
        """
        pass

    def test_products_lidvid_collections_latest(self):
        """Test case for products_lidvid_collections_latest

        deprecated  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
