# coding: utf-8

"""
    PDS Registry Search API

    Registry API enabling advanced search on PDS data and metadata. The API provides end-points to search for bundles, collections and any PDS products with advanced search queries. It also enables to browse the archive hierarchically downward (e.g. collection/s products) or upward (e.g. bundles containing a product).   # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: pds-operator@jpl.nasa.gov
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import pds.api_client
from pds.api_client.api.by_product_classes_api import ByProductClassesApi  # noqa: E501
from pds.api_client.rest import ApiException


class TestByProductClassesApi(unittest.TestCase):
    """ByProductClassesApi unit test stubs"""

    def setUp(self):
        self.api = pds.api_client.api.by_product_classes_api.ByProductClassesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_class_list(self):
        """Test case for class_list

        returns all PDS products of the given PDS product class that meet all given constraints.   # noqa: E501
        """
        pass

    def test_classes(self):
        """Test case for classes

        returns a list of the available PDS product class at this API. This is not all of the PDS product class available in the database, but simply the names that can be used in the /classes/{class} endpoints.   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
