# coding: utf-8

"""
    rtu mirea vuc schedule

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rtu_mirea_vuc_schedule_client.models.week_schedule import WeekSchedule  # noqa: E501

class TestWeekSchedule(unittest.TestCase):
    """WeekSchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WeekSchedule:
        """Test WeekSchedule
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WeekSchedule`
        """
        model = WeekSchedule()  # noqa: E501
        if include_optional:
            return WeekSchedule(
                var_date = '',
                datetime = '',
                subjects = [
                    rtu_mirea_vuc_schedule_client.models.subject.Subject(
                        name = '', 
                        auditory = '', 
                        teacher = '', 
                        lesson = rtu_mirea_vuc_schedule_client.models.lesson.Lesson(
                            topic = 56, 
                            lesson = 56, 
                            type = '', ), )
                    ],
                coordinates = None
            )
        else:
            return WeekSchedule(
        )
        """

    def testWeekSchedule(self):
        """Test WeekSchedule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
