# coding: utf-8

"""
    rtu mirea vuc schedule

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rtu_mirea_vuc_schedule_client.api.workbook_api import WorkbookApi  # noqa: E501


class TestWorkbookApi(unittest.TestCase):
    """WorkbookApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkbookApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_workbook_relevance_api_v1_workbook_relevance_get(self) -> None:
        """Test case for get_workbook_relevance_api_v1_workbook_relevance_get

        Get Workbook Relevance  # noqa: E501
        """
        pass

    def test_get_workbooks_api_v1_workbook_get(self) -> None:
        """Test case for get_workbooks_api_v1_workbook_get

        Get Workbooks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
