# coding: utf-8

"""
    rtu mirea vuc schedule

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rtu_mirea_vuc_schedule_client.models.workbook_settings import WorkbookSettings  # noqa: E501

class TestWorkbookSettings(unittest.TestCase):
    """WorkbookSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkbookSettings:
        """Test WorkbookSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkbookSettings`
        """
        model = WorkbookSettings()  # noqa: E501
        if include_optional:
            return WorkbookSettings(
                day_range = rtu_mirea_vuc_schedule_client.models.shape.Shape(
                    rows = 56, 
                    cols = 56, ),
                year_range = rtu_mirea_vuc_schedule_client.models.shape.Shape(
                    rows = 56, 
                    cols = 56, ),
                days_in_week_column_number = None,
                platoon_column_number = None,
                subject_rows_number = None
            )
        else:
            return WorkbookSettings(
        )
        """

    def testWorkbookSettings(self):
        """Test WorkbookSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
