
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-30T15:15:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7ebf1dd4ec99236b35090c28b0d4019d0c32d20",
 "version": "0.8.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
