
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T13:54:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1852c926ab6a7dcfb83c9b4c130e2bfb4efd99b9",
 "version": "3.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
