
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-27T12:58:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f40c6649d2a7a95550952ee6c79f3982d3414252",
 "version": "2.4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
