
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-27T16:40:57-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8f647fe10c9c5f939de345fe5b98dd1ac39fa7a",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
