
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T05:49:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d281cdf955706b82c0f0a848a669e1337d65de7",
 "version": "1.20.0.post0.dev27"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
