
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-27T15:10:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "30200963f40e901b042dbe52251a9151c1b3f750",
 "version": "1.6.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
