class Dimension:
    COMPREHENSION = "知识能力维度"
    COMPREHENSION_KNOWLEDGE_MASTER = "知识掌握"
    COMPREHENSION_LANGUAGE_UNDERSTANDING = "语言理解"
    COMPREHENSION_LOGIC_REASONING = "逻辑推理"
    COMPREHENSION_PROFESSIONAL_FILED = "专业领域"
    ETHIC_ALIGN = "伦理对齐维度"
    ROBUST_SAFETY = "鲁棒安全维度"


