
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-28T11:15:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "951b409d4ba8cf2e20084283ee07386d8fff9852",
 "version": "0.53"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
