
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T07:43:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "888a273de2c3896beb0629ed5adf6ee94bf04df7",
 "version": "1.20.0.post0.dev39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
