# Generated by Django 4.2.7 on 2023-11-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sada", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
