# Generated by Django 3.2.7 on 2021-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobinobi_core', '0002_organisation_organisationclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
    ]
