# Generated by Django 4.2.7 on 2023-11-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sada", "0002_alter_product_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "interval_count",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "type",
                    models.CharField(
                        choices=[("one_time", "One Time"), ("recurring", "Recurring")],
                        max_length=255,
                    ),
                ),
                ("unit_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="sada.product",
                    ),
                ),
            ],
        ),
    ]
