
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-28T21:59:32-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "03923a2927569704b7707b78e33d350966451715",
 "version": "6.24.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
