
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-24T18:59:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "182c82fc3ff846f06c98d2fd8f21ee86e87a3ea3",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
