
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-29T05:05:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a05f804e94dec99dd77e198d019721df27d2a140",
 "version": "1.20.0.post0.dev21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
