"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import qwak.execution.v1.jobs.job_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ApplyJobRecordRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOB_RECORD_FIELD_NUMBER: builtins.int
    @property
    def job_record(self) -> qwak.execution.v1.jobs.job_pb2.JobRecord:
        """a Job Record to create or replace"""
    def __init__(
        self,
        *,
        job_record: qwak.execution.v1.jobs.job_pb2.JobRecord | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["job_record", b"job_record"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["job_record", b"job_record"]) -> None: ...

global___ApplyJobRecordRequest = ApplyJobRecordRequest

class ApplyJobRecordResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ApplyJobRecordResponse = ApplyJobRecordResponse

class InitPaginationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEATURESET_ID_FIELD_NUMBER: builtins.int
    featureset_id: builtins.str
    """the featureset id for which to start a pagination"""
    def __init__(
        self,
        *,
        featureset_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["featureset_id", b"featureset_id"]) -> None: ...

global___InitPaginationRequest = InitPaginationRequest

class InitPaginationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECORD_COUNT_FIELD_NUMBER: builtins.int
    MAX_RECORD_ID_FIELD_NUMBER: builtins.int
    record_count: builtins.int
    """Number of records found for this Featureset at the time of querying
    this is used mainly by the client to plan things like number of pages etc.
    """
    max_record_id: builtins.int
    """the current highest record id for this FS. this is the anchor
    to use on subsequent requests if the caller wants to achieve
    a view of a static list
    """
    def __init__(
        self,
        *,
        record_count: builtins.int = ...,
        max_record_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["max_record_id", b"max_record_id", "record_count", b"record_count"]) -> None: ...

global___InitPaginationResponse = InitPaginationResponse

class ListJobsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEATURESET_ID_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_NUMBER_FIELD_NUMBER: builtins.int
    MAX_RECORD_ID_FIELD_NUMBER: builtins.int
    featureset_id: builtins.str
    """featureset id"""
    page_size: builtins.int
    """The page size to use for the response - the number of results in the response
    is the minimum of the page_size and number of matching rows.
    - a negative value means all results will be returned (in that case page_number is ignored)
    """
    page_number: builtins.int
    """The page number to use"""
    max_record_id: builtins.int
    """The max record id to use as anchor - this is the value returned from InitPagination"""
    def __init__(
        self,
        *,
        featureset_id: builtins.str = ...,
        page_size: builtins.int = ...,
        page_number: builtins.int = ...,
        max_record_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["featureset_id", b"featureset_id", "max_record_id", b"max_record_id", "page_number", b"page_number", "page_size", b"page_size"]) -> None: ...

global___ListJobsRequest = ListJobsRequest

class ListJobsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOB_RECORDS_FIELD_NUMBER: builtins.int
    @property
    def job_records(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[qwak.execution.v1.jobs.job_pb2.JobRecord]:
        """All rows, sorted by the job record start time (event time)"""
    def __init__(
        self,
        *,
        job_records: collections.abc.Iterable[qwak.execution.v1.jobs.job_pb2.JobRecord] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["job_records", b"job_records"]) -> None: ...

global___ListJobsResponse = ListJobsResponse

class DeleteFeaturesetJobsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEATURESET_ID_FIELD_NUMBER: builtins.int
    featureset_id: builtins.str
    """The featureset id"""
    def __init__(
        self,
        *,
        featureset_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["featureset_id", b"featureset_id"]) -> None: ...

global___DeleteFeaturesetJobsRequest = DeleteFeaturesetJobsRequest

class DeleteFeaturesetJobsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DELETED_JOB_RECORD_COUNT_FIELD_NUMBER: builtins.int
    deleted_job_record_count: builtins.int
    def __init__(
        self,
        *,
        deleted_job_record_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["deleted_job_record_count", b"deleted_job_record_count"]) -> None: ...

global___DeleteFeaturesetJobsResponse = DeleteFeaturesetJobsResponse

class GetLastSuccessfulJobByFeaturesetIdRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FEATURESET_ID_FIELD_NUMBER: builtins.int
    featureset_id: builtins.str
    def __init__(
        self,
        *,
        featureset_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["featureset_id", b"featureset_id"]) -> None: ...

global___GetLastSuccessfulJobByFeaturesetIdRequest = GetLastSuccessfulJobByFeaturesetIdRequest

class GetLastSuccessfulJobByFeaturesetIdResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOB_RECORD_FIELD_NUMBER: builtins.int
    @property
    def job_record(self) -> qwak.execution.v1.jobs.job_pb2.JobRecord: ...
    def __init__(
        self,
        *,
        job_record: qwak.execution.v1.jobs.job_pb2.JobRecord | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["job_record", b"job_record", "job_record_resp", b"job_record_resp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["job_record", b"job_record", "job_record_resp", b"job_record_resp"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["job_record_resp", b"job_record_resp"]) -> typing_extensions.Literal["job_record"] | None: ...

global___GetLastSuccessfulJobByFeaturesetIdResponse = GetLastSuccessfulJobByFeaturesetIdResponse
