
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-30T15:00:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f776bd901f874ef69bf60d159050a28479751eb7",
 "version": "0.8.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
