
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-26T02:14:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d20386ee42066c8c50233f4cc293b518693b83cf",
 "version": "1.4.dev2348"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
