
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-28T12:02:38-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c3222e3f0ca647cd07ff41c4c33ee4f9ee413686",
 "version": "0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
