# Generated by Django 4.2.7 on 2023-11-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "edc_form_runners",
            "0002_remove_issue_unique_label_lower_subject_identifier_etc_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="issue",
            name="unique_label_lower_subject_identifier_etc",
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="edc_form_ru_label_l_ce3dda_idx",
        ),
        migrations.RemoveIndex(
            model_name="issue",
            name="edc_form_ru_subject_10bb16_idx",
        ),
        migrations.AddField(
            model_name="issue",
            name="panel_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["label_lower", "field_name", "panel_name", "short_message"],
                name="edc_form_ru_label_l_c7917b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=[
                    "subject_identifier",
                    "visit_code",
                    "visit_code_sequence",
                    "panel_name",
                    "short_message",
                ],
                name="edc_form_ru_subject_1df4e6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="issue",
            constraint=models.UniqueConstraint(
                fields=(
                    "label_lower",
                    "subject_identifier",
                    "field_name",
                    "visit_code",
                    "visit_code_sequence",
                    "visit_schedule_name",
                    "schedule_name",
                    "panel_name",
                ),
                name="unique_label_lower_subject_identifier_etc",
            ),
        ),
    ]
