# Generated by Django 4.2.7 on 2023-11-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "edc_form_runners",
            "0003_remove_issue_unique_label_lower_subject_identifier_etc_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="issue",
            name="unique_label_lower_subject_identifier_etc",
        ),
        migrations.RenameField(
            model_name="issue",
            old_name="ignore_formfields",
            new_name="exclude_formfields",
        ),
        migrations.AddConstraint(
            model_name="issue",
            constraint=models.UniqueConstraint(
                fields=(
                    "subject_identifier",
                    "label_lower",
                    "field_name",
                    "panel_name",
                    "visit_code",
                    "visit_code_sequence",
                    "visit_schedule_name",
                    "schedule_name",
                ),
                name="unique_label_lower_subject_identifier_etc",
            ),
        ),
    ]
