
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-11-28T11:50:05-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf5cb5748b5a43e4d5fb38b9f30b36c6ae32cba2",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
